[package]
name = "blivedm_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
client = { git = "https://github.com/Mufanc/blivedm_rs", branch = "statistics" }
env_logger = "0.11"
futures-channel = "0.3"
futures-util = "0.3"
log = "0.4"
tokio = { version = "1", features = ["full"] }
